export enum SignalStatusEnum {
    CrackClose = -1,
    Close = 0,
    Success = 1,
    ReConnecting = 2,
    ReConnected = 3,
    LoginSuccess = 4,
}

export enum NotifyActionTypeEnum {
    Text = 1,
    Html = 2,
    OTP = 3,
    System = 4,
    MyArticleApproved = 5,
    MyArticleChanged = 6,
    MyArticleMissingSeo = 7,

    //MyArticleDeny = 8,
    MyArticlePublished = 9,
    ArticleSendToEditor = 10,
    ArticleSendToPublish = 11,
    ArticleAssignToMe = 12,
    ArticleHasDiscuss = 13,
    ArticleHasComment = 14,
    MyRoleChanged = 15,
    ImpersonateFrom = 16,
    ImpersonateTo = 17,
    ImpersonateExpired = 18,
    CommentNeedApprove = 19,
    SyncNewsToEs = 20,
    Lock = 21,
    UnLock = 22,
    VideoToGif = 23,
    DashboardWidgetChange = 24,
    LoginNotify = 25,
    MobileCategory = 26,
    MobileArticle = 27,
    UserSignIn = 28,
    MessageSent = 29,
    MessageReceived = 30,

    UserAddToDepartment = 31,
    UserRemoveFromDepartment = 32,
    MyArticleDenyFromEditor = 33,
    MyArticleDenyFromPublish = 34,
    MyArticleEditing = 35,
    CommentChangeStatus = 36,
    VideoAddWatermark = 37,
    VbeeAudioConvertSuccess = 38,
    Podcast = 39,
    LotteryTrial = 40,
    LotteryTrialExpired = 41,
    ArticlePublish = 42,
    ArticleUnPublish = 43,
    ArticleChange = 44,
    UserActivityStart = 45,
    UserActivityEnd = 46,
    ContentOnlineInterviewQuestionAndAnswerReplace = 47,
    ContentOnlineInterviewGuestAdd = 48,
    ContentOnlineInterviewGuestChange = 49,
    ContentOnlineInterviewGuestStatusChange = 50,
    ContentOnlineInterviewQuestionSort = 51,
    ContentOnlineInterviewQuestionAndAnswerPublish = 52,
    ContentOnlineInterviewQuestionAndAnswerUnPublish = 53,
    ContentOnlineInterviewQuestionAndAnswerRemove = 54,
    MessageChange = 55,
    MessageRemove = 56,
    CommentApproved = 57,
    CommentReplyApproved = 58,
    CommentEmotionReact = 59,
    PremiumOrderSuccess = 60,
    PremiumExpireNotice = 61,
    StolenVehicleTrackingEvent = 108,
    EmergencyEvent = 109,
    ImmobilizerEvent = 110,
}

export enum UserActivityTypeEnum {
    Article = 1,
}

export enum ConnectionStringEnum {
    OnReconnecting = 'OnReconnecting',
    OnReconnected = 'OnReconnected',
    OnConnected = 'OnConnected',
    OnLoginSuccess = 'OnLoginSuccess',
    Onclose = 'Onclose',
}
